### ISSUE TITLE
Handle preordered albums

### ISSUE THREAD

**Issue by disconnect78** [meeb/bandcampsync#16]
When I synced my library I had an album preordered which had some of the tracks available. These were downloaded and a `bandcamp_item_id.txt` file was created in the album folder. This means that now the album has been properly released, it's being skipped so I only have the partial album downloaded.

Now that I realise this happens, I can manually delete the `bandcamp_item_id.txt` from the folder when a preordered album is released; but it may be preferable to simply skip downloading unreleased preorders altogether, eg. in `__init__.py`:

```python
...
local_path = local_media.get_path_for_purchase(item)
if item.is_preorder == True:
    log.info(f'Item is preorder, skipping: "{item.band_name} / {item.item_title}" '
             f'(id:{item.item_id})')
    continue
elif local_media.is_locally_downloaded(item, local_path):
...
```

**Comment by meeb** [comment]
Sounds like a decent addition, thanks! Do you want to create a PR for that?

**Comment by meeb** [comment]
I've copy/pasted the above and checked it, seems fine.
