### ISSUE TITLE
Sometimes, mp3 files are left with a `*.mp3-320` file extension

### ISSUE THREAD

**Issue by evmmc** [meeb/bandcampsync#18]
Basically, title.

Steps to reproduce - download a large collection, a number of tracks usually are bound to have the wrong file extension.

Fine the files with:

    find  /your/directory/path -name '*.mp3-320'

Workaround: rename the files with:

    find /your/directory/path -type f -name '*mp3-320' -exec sh -c 'mv "$1" "${1%-320}"' _ {} \;

**Comment by meeb** [comment]
This was because single file downloads had to use the bandcamp supplied format as the file extension and this sometimes included the bitrate along with the format. The above commit should fix this and I'll bundle it into a release later. Thanks for the issue.
