### ISSUE TITLE
No interpolation on directory creation failure error message

### ISSUE THREAD

**Issue by rajiv** [meeb/bandcampsync#23]
When `bandcampsync` cannot create a directory, it outputs:

```
Failed to create directory: {local_path} ({e}), skipping purchase...
```

It should print the value of `local_path` and `e`. This line is the likely culprit:

https://github.com/meeb/bandcampsync/blob/d26f5de60a429cad12a617b9c2d22da6114715df/bandcampsync/__init__.py#L48

**Comment by meeb** [comment]
Ah yes, the stealthy missing `f`. I'll add that in short, thanks for the issue.

**Comment by meeb** [comment]
Fixed in the above commit and will be bundled into the next release.
