### ISSUE TITLE
Handle slashes in artist, title and track names

### ISSUE THREAD

**Issue by meeb** [meeb/bandcampsync#3]
Artists, title and track names (when track names are for single tracks and the title is used) can contain forward and backslashes. These can be converted by `pathlib` to be valid subdirectory paths. Slashes should be replaced by something filesystem path agnostic like hyphens.

**Comment by Gondolindrim** [comment]
Might be worth taking a look into special characters in general. Some music names have apostrophes, hyphens and all sorts of characters
